import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CalendarDays, Check, Clock3, Heart, Sparkles } from "lucide-react";
import { Container } from "@/components/ui/Container";
import { SectionHeading } from "@/components/SectionHeading";
import { ServiceCard } from "@/components/ServiceCard";
import { BookingCta } from "@/components/BookingCta";
import { services, testimonials } from "@/data/site";

const hero = "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1800&q=88";
const interior = "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=1400&q=85";
const detail = "https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=1200&q=85";

export default function HomePage() {
  return <>
    <section className="hero-salon overflow-hidden"><Container className="grid min-h-[720px] items-center gap-10 py-14 lg:grid-cols-[.82fr_1.18fr] lg:py-16">
      <div className="reveal relative z-10"><p className="text-xs font-bold uppercase tracking-[.24em] text-[#b76e79]">Beauty, thoughtfully done.</p><h1 className="mt-5 max-w-xl font-serif text-6xl leading-[.98] text-[#241d21] md:text-7xl xl:text-8xl">Your beauty.<br/><i>Your ritual.</i></h1><p className="mt-7 max-w-lg text-base leading-7 text-[#746a70]">A calm, modern salon in the heart of Bangalore for considered hair, beauty, bridal and grooming experiences.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/booking" className="inline-flex items-center gap-2 rounded-full bg-[#302426] px-7 py-3.5 text-sm font-semibold text-white shadow-xl shadow-[#b76e79]/20 transition hover:-translate-y-0.5 hover:bg-[#211a1b]"><CalendarDays size={17}/> Book a Visit</Link><Link href="/services" className="inline-flex items-center gap-2 rounded-full border border-[#d8c0bd] bg-white/70 px-7 py-3.5 text-sm font-semibold text-[#925560] backdrop-blur transition hover:bg-white">Explore Services <ArrowRight size={17}/></Link></div><div className="mt-10 grid max-w-lg grid-cols-3 gap-4 border-t border-[#d8c8c4] pt-6 text-xs text-[#746a70]"><span><b className="block font-serif text-2xl text-[#241d21]">11+</b> years of craft</span><span><b className="block font-serif text-2xl text-[#241d21]">4.9/5</b> guest rating</span><span><b className="block font-serif text-2xl text-[#241d21]">1:1</b> consultations</span></div></div>
      <div className="image-wrap relative min-h-[530px] overflow-hidden rounded-[42px] shadow-2xl lg:min-h-[640px]"><Image src={hero} alt="Woman having her hair styled in a modern salon" fill priority sizes="(min-width: 1024px) 60vw, 100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#241d21]/55 via-transparent to-transparent"/><div className="glass absolute left-5 top-5 rounded-full px-4 py-2 text-xs font-semibold tracking-[.14em] text-[#925560]">LUMINA BEAUTY STUDIO</div><div className="glass absolute bottom-5 left-5 right-5 rounded-[26px] p-5"><p className="font-serif text-2xl">A little luxury in your everyday.</p><p className="mt-1 text-sm text-[#746a70]">Hair · Beauty · Bridal · Grooming</p></div></div>
    </Container></section>

    <section className="border-y border-[#eadedb] bg-white py-5"><Container className="flex flex-wrap items-center justify-center gap-x-10 gap-y-3 text-xs font-semibold uppercase tracking-[.18em] text-[#95888d]"><span className="flex items-center gap-2"><Sparkles size={15}/> Premium products</span><span className="flex items-center gap-2"><Heart size={15}/> Personalised care</span><span className="flex items-center gap-2"><Clock3 size={15}/> Relaxed experience</span><span className="flex items-center gap-2"><Check size={15}/> Hygiene first</span></Container></section>

    <section className="section"><Container><SectionHeading eyebrow="Our Services" title="Beautiful results, never one-size-fits-all." description="Every appointment begins with a conversation, then becomes a personalised ritual designed around you."/><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{services.map(s => <ServiceCard key={s.slug} service={s}/>)}</div></Container></section>

    <section className="section bg-[#fcf8f5]"><Container className="grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div className="image-wrap relative aspect-[4/5] overflow-hidden rounded-[38px] shadow-xl"><Image src={interior} alt="Warm, elegant Lumina salon interior" fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover"/><div className="glass absolute bottom-5 left-5 rounded-2xl p-4"><p className="font-serif text-xl">Come in. Exhale.</p><p className="text-xs text-[#746a70]">Residency Road · Bangalore</p></div></div><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#b76e79]">The Lumina Difference</p><h2 className="mt-3 max-w-xl font-serif text-5xl leading-tight text-[#241d21]">More than a salon. A moment for yourself.</h2><p className="mt-5 max-w-xl text-[15px] leading-7 text-[#746a70]">We built Lumina to make beauty appointments feel less rushed and more personal. Our artists listen first, recommend honestly and create results you can actually live with.</p><div className="mt-7 grid gap-3 text-sm">{["Consultation-led appointments","Professional products selected for your needs","Quiet, hygienic and beautifully considered spaces"].map(x => <div key={x} className="flex items-center gap-3"><Check size={18} className="text-[#b76e79]"/><span>{x}</span></div>)}</div><Link href="/about" className="mt-8 inline-flex items-center gap-2 rounded-full border border-[#d8c0bd] px-5 py-3 text-sm font-semibold text-[#925560] transition hover:bg-white">Discover Our Story <ArrowRight size={16}/></Link></div></Container></section>

    <section className="section"><Container className="grid items-center gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#b76e79]">The Studio</p><h2 className="mt-3 font-serif text-5xl">Come for the transformation. Stay for the feeling.</h2><p className="mt-5 text-[15px] leading-7 text-[#746a70]">Soft light, warm textures and a team that remembers how you like your coffee. Lumina is designed to feel elevated without ever feeling intimidating.</p><Link href="/gallery" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#925560]">Step inside <ArrowRight size={16}/></Link></div><div className="image-wrap relative aspect-[16/9] overflow-hidden rounded-[36px] shadow-xl"><Image src={detail} alt="Hair styling detail at Lumina" fill sizes="(min-width: 1024px) 65vw, 100vw" className="object-cover"/></div></Container></section>

    <section className="section bg-[#fcf8f5]"><Container><SectionHeading eyebrow="Client Love" title="Kind words from our guests."/><div className="mt-10 grid gap-5 md:grid-cols-3">{testimonials.slice(0,3).map(t => <article key={t.name} className="rounded-3xl border border-[#eadedb] bg-white p-7 shadow-sm"><div className="text-[#e2a6ad]">★★★★★</div><p className="mt-5 text-sm leading-7 text-[#746a70]">“{t.quote}”</p><div className="mt-6"><strong className="text-sm">{t.name}</strong><p className="mt-1 text-xs text-[#9b8f94]">{t.service}</p></div></article>)}</div><BookingCta/></Container></section>
  </>;
}
